services:
  # Vue.js frontend
  frontend:
    build:
      context: ./frontend
      args:
        ENV: ${ENV:-dev}
    ports:
      - '8080:80'
    depends_on:
      - backend

  # Node.js backend service
  backend:
    build:
      context: ./backend
      args:
        ENV: ${ENV:-dev}
    ports:
      - '3000:3000'
    depends_on:
      - db

  # MySQL database service
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: vuetest
      MYSQL_USER: devUser
      MYSQL_PASSWORD: devUser
    ports:
      - '3306:3306'
    volumes:
      - ./database/vuetest.sql:/docker-entrypoint-initdb.d/init.sql
