# .github/workflows/ci.yml
name: Gihub CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Hub credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker images
        run: |
          # Build and push frontend Docker image
          docker buildx build --file frontend/Dockerfile --tag raymondlwy/sales-order-management-frontend::latest --push ./frontend

          # Build and push backend Docker image
          docker buildx build --file backend/Dockerfile --tag raymondlwy/sales-order-management-backend::latest --push ./backend
