# .github/workflows/cd.yml
name: Gihub CD Pipeline

on:
  workflow_run:
    workflows: ['Gihub CI Pipeline']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Drop the process
            docker stop frontend && docker rm frontend
            docker stop backend && docker rm backend

            # Pull container images
            docker pull raymondlwy/sales-order-management-frontend:latest
            docker pull raymondlwy/sales-order-management-backend:latest

            # Run the frontend container
            docker run --name frontend \
              -p 8080:80 \
              -d raymondlwy/sales-order-management-frontend:latest

            # Run the backend container
            docker run --name backend \
              -p 3000:3000 \
              -d raymondlwy/sales-order-management-backend:latest
