# .github/workflows/ci.yml
name: Gihub CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Hub credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker images
        run: |
          docker buildx build --tag my-docker-image:latest --push .

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.ci.yml up --build --abort-on-container-exit --exit-code-from backend

      - name: Stop Docker Compose
        if: always()
        run: docker-compose -f docker-compose.ci.yml down
